language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: DJPZggRRw8vv0Joya/pIj5v9DWIHiMpiZGpSzHXhmRvBNTbgmwz/LxQhEgeJGhE5W0PYLEB7jS8oGiYZQd4keadKzyALPNimHxxT1NJ3+ujhYm83x0MfO9kvnwAdEhE1PMmYkFHVSL/DrNF5iLX77ECkoJeNwHBppA4eYHISJf/OG4eC3JKFnQpDSwQr5tvOxWgdtl2ghZSOynN9VyiW1pfovs/MWiXcB+4hNAYThY1fJRkd8MwqbPSA2F6YIrM28i7RC37D6Nf7TPwF4MxXQ0w+Ibg3y7jCjZR0inuoVnYo2YJEEb8rtr8e0rYTOaZ4ess2gIHZoTXV2r+RByiJ8uq3Pv7cUgzciqEUB9BxWXvbKcw7lWq4aVFd5EFXkK9qarEWMWGa/us/ZKus9IS6rOVG7cFLupkmO6HxcsOmKBnvlVLsp6gDe1MBsx6YPemnQobfrHRQ847IVYR+Vc+GCHjijEyVIsgI3tl5mz+yNhlWCCpuHskEDDithlH9TipO3e11Jw3H6w09lTQP3wYhtrho6+XoyGKOd0OhS5DMnbAQeneb4Edd6uUqsTNzc50G8hrT6JNTdKAleUeHmck6ggqfpKlunj9GV7LOtfB7SlImLraNvF2g9fbhP+3GT2nU41X19LOWTVFPs1rWZVfpZcHGkalsSK0daTUdzv4dr8I=
  on:
    tags: true
    repo: BenjaminDavison/aws_data_toolkit
    python: 3.8
